			$(function(){
				$("select").selectbox();
			});	
	/* ------ Code generated by IxEdit (ixedit.com). ------ */
	if(window.ixedit){ixedit.deployed = true};
	if(window.jQuery){jQuery(function(){
		(function(){ jQuery('div.templates-wrapper a').bind('mouseover', function(event, ui)
			{
				var target = jQuery('div.templates-wrapper a.active');
				target.removeClass('active');
				var target = jQuery(event.currentTarget);
				target.addClass('active'); 
				var target = jQuery('img#frontpreview').attr('src',this.id);
			
				
			}
		);
		
		jQuery('div.templates-wrapper a').bind('click', function(event, ui)
			{
				var name=this.name;
				var arr=name.split("&");
				var newArr=arr[0].split("=");
				if(newArr[1]==17)
				{
				var imagePath=$(this).attr('id');
				var folderName= imagePath.replace(/\\/g,'/').replace(/\/[^\/]*$/, '');
				var splitFolder=folderName.replace(/\\/g,'/').replace( /.*\//, '' );
				
				var folderTypePath= folderName.replace(/\\/g,'/').replace(/\/[^\/]*$/, '');
				var folderType=folderTypePath.replace(/\\/g,'/').replace( /.*\//, '' );
				if(folderType=="A5")
				folderType=1;
				if(folderType=="Long")
				folderType=2;
				if(folderType=="Square")
				folderType=3;
				$('#calType').val(folderType);//alert(folderType);
					
				var calType=$('#calType').val();
				window.location="cart_design.php?"+this.name+"&folder="+splitFolder+"&type="+calType;
				
				
					
				}
				else
				window.location="cart_design.php?"+this.name;
				
			}
		)
		
		
		
		})();
	})};

 $(document).ready(function() {
 	var session_bc_t = 
	jQuery("a#"+session_bc_t).addclass("active");
	jQuery('img#frontpreview').attr('src',"images/"+ session_bc_t +".jpg");
 });
