(function($) {
eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('0 7=/^b\\((\\1+),\\2*(\\1+),\\2*(\\1+)\\)$/;0 8=/^[a-5-4-9]{6}|[a-5-4-9]{3}$/;0 c=\'\';',13,13,'var|d|s||F0|fA||rgbRE|colorRE|||rgb|rgbString'.split('|'),0,{}))
	function mouseEnterColor(event){eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('5=$(f.n).b("e-g");4 2=5.p(q);4 r=2;6(2!=c){d(2[0]);t(4 i=1;i<=3;++i){2[i]=j(2[i]).k(l);6(2[i].m==1)2[i]=\'0\'+2[i]}4 7=2.o(\'\');$("#8").9(7).a()}s{$("#8").9(5.h(1)).a()}',30,30,'||parts||var|rgbString|if|hexString|mlSelectedColorText|val|keyup|css|null|delete|background|event|color|substring||parseInt|toString|16|length|target|join|match|rgbRE|newParts|else|for'.split('|'),0,{}))}
	function mouseClickColor(){eval(function(p,a,c,k,e,r){e=String;if(!''.replace(/^/,String)){while(c--)r[c]=k[c]||c;k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('0();',2,1,'colorSave'.split('|'),0,{}))}
	function textKeyUp(event){eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('0=$(2.6).3();1(0.5(b)){7(0,8)}1(2.9==a){4()}',12,12,'color|if|event|val|colorSave|match|target|colorChange|rgbString|keyCode|13|colorRE'.split('|'),0,{}))}
	function colorChange(color,rgbString){eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('2 8=e.i(b);2 4=8;$("#d").6("h-3","#"+3);2 7=$(\'#l\').9();2 a=7.f("g");2 5=a[0];$(\'#\'+5+\'j\').6("3","#"+3);4.k(0,1);$(\'#\'+5+\'c\').9(4);',22,22,'||var|color|newParts|spltId|css|fieldname|parts|val|idParts|rgbRE|_fontcolor|mlSelectedColorDiv|rgbString|split|_|background|match|_text|splice|current_selected_text'.split('|'),0,{}))}


	function colorSave(){eval(function(p,a,c,k,e,r){e=String;if(!''.replace(/^/,String)){while(c--)r[c]=k[c]||c;k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('1($("#2").3("4")){0=$("#5").6();1(0.7(8)){$("#2").3("4")(0)}}',9,9,'color|if|mlColorPicker|data|mlOnChange|mlSelectedColorText|val|match|colorRE'.split('|'),0,{}))}
	
	function close(){eval(function(p,a,c,k,e,r){e=String;if(!''.replace(/^/,String)){while(c--)r[c]=k[c]||c;k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$("#0").1().2("3");',4,4,'mlColorPicker|hide|removeData|mlOnChange'.split('|'),0,{}))}


	function createColorPicker(){eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('A q=["#C","#D","#E","#H","#I","#K","#L","#M","#N","#O","#P","#R","#V","#10","#16","#17","#18","#1a","#1b","#1e","#1h","#1l","#1o","#1p","#1r","#1s","#1u","#1v","#1w","#1x","#1y","#1z","#1A"];$(".d").m((\'<1 2="F:G;" 7="b"><1 7="J" 2="3:4;"></1><1 8="c" 2="n:o;3:4;"><Q 1E="S/T.U"  2="n:o;3:4;"/>&r;&r;W</1><1 8="X" 2="3:4;">Y</1><Z 7="s" 11="12" 13="14" 15="6" 2="3:4;"><1 7="5" 2="3:l;"></1></1>\'))A k=$("#5")$.19(q,f(i,a){k.m(\'<1 8="1c"><1 8="1d"><1 8="p" 7="\'+a+\'" 2="1f-c:\'+a+\'" /></1></1>\')});$(\'.p\').1g("g",1i);$("#s").1j(1k);$(\'#b,#b *\').g(f(e){e.1m()})$(".c").g(f(){1n(h.j(\'5\').2.3!="4"){$("#5").1q(t);$(".d").u(1t);h.j(\'5\').2.3="4";$("#v").w({x:0,y:-z,9:$.9.B})}1C{$(".d").u(1D);$("#5").1B(t);h.j(\'5\').2.3="l";$("#v").w({x:-z,y:0,9:$.9.B})}});',62,103,'|div|style|display|none|mlColors||id|class|easing||mlColorPicker|color|color_box||function|click|document||getElementById|colorHolder|block|append|cursor|pointer|mlColor|colors|nbsp|mlSelectedColorText|200|height|arrow|rotate|angle|animateTo|90|var|easeInOutExpo|ff7572|ff689c|ff309a|position|absolute|cd0086|9a0065|mlSelectedColorDiv|ce0000|690000|d51476|ff9a23|ff6600|a15616|img|65009b|images|down_arrow|png|9a2f9b|COLOR|select|SELECTED|input|7b53a0|type|text|value|6E6D6B|maxlength|56b6b5|8b95db|0087cc|each|2d649a|003367|mlColorhov|mlColorborder|3fa853|background|bind|659a00|mouseEnterColor|keyup|textKeyUp|453928|stopPropagation|if|ffffff|e8435b|hide|660033|663333|20|666633|669933|66CC33|666666|000066|003366|006666|show|else|50|src'.split('|'),0,{}))}
		

	
	$.fn.mlColorPicker = function(settings) {
eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('9 1={\'2\':3(a){}};4(5)$.8(1,5);4($("#6").7==0){b()c.d(3(){$("#6").e().f("g").h("i",1["2"])})}',19,19,'|config|onChange|function|if|settings|mlColorPicker|length|extend|var||createColorPicker|this|each|hide|show|slow|data|mlOnChange'.split('|'),0,{}))
return this;
	};
		

})(jQuery);
